[package]
name = "hpc_srv"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/i18n-site/hpc_srv.git"
homepage = "https://github.com/i18n-site/hpc_srv/tree/main/hpc_srv"
description = "hpc server"

[dependencies]
hpc = { path = "../../hpc/rust/hpc" }
mod = { path = "../mod" }
pb = { path = "../gen/pb" }

aok = "0.1.17"
axum = { version = "0.8.1", features = ["tracing", "macros"] }
axum_layer = "0.1.8"
genv = "0.1.15"
loginit = "0.1.18"
pb-jelly = "0.0.17"
static_ = "0.1.14"
static_init = "1.0.3"
tokio = { version = "1.43.0", features = ["macros", "rt", "rt-multi-thread"] }
req_ = { version = "0.1.27", features = ["cookie"] }

[package.metadata.cargo-machete]
ignored = ["pb-jelly", "pb", "mod"]
